int32 current_threshold_contact
int32 current_threshold_final
int32 max_belt_travel_mm
float32 phalange_delta_rad
float32 gripper_closed_thresh
bool check_phalanges
---
bool success
float32 opening_current
float32 opening_angle
float32 p1_angle
float32 p2_angle
